tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mas-cli/tap"
brew "aria2"
brew "bat"
brew "bottom"
brew "readline"
brew "conan"
brew "curl"
brew "delta"
brew "dust"
brew "fd"
brew "icu4c"
brew "ffmpeg"
brew "fzf"
brew "gcc"
brew "git"
brew "gitui"
brew "pinentry"
brew "gnupg"
brew "kondo"
brew "lsd"
brew "luajit-openresty"
brew "lux"
brew "mas"
brew "mysql", restart_service: true
brew "navi"
brew "neovim"
brew "node"
brew "openjdk"
brew "pandoc"
brew "python@3.8"
brew "r"
brew "ripgrep"
brew "rustup-init"
brew "starship"
brew "texlab"
brew "yarn"
brew "zellij"
brew "zoxide"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "alacritty"
cask "android-file-transfer"
cask "basictex"
cask "bitwarden"
cask "blackhole-2ch"
cask "clash-for-windows"
cask "clashx-pro"
cask "crossover"
cask "cryptomator"
cask "dingtalk"
cask "drawio"
cask "font-fira-code-nerd-font"
cask "frhelper"
cask "geogebra"
cask "gimp"
cask "google-chrome"
cask "inkscape"
cask "julia"
cask "keepingyouawake"
cask "keka"
cask "licecap"
cask "lulu"
cask "lyricsx"
cask "miniconda"
cask "mathpix-snipping-tool"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "motrix"
cask "mounty"
cask "neteasemusic"
cask "obs"
cask "onlyoffice"
cask "oversight"
cask "paragon-ntfs"
cask "pdfsam-basic"
cask "qq"
cask "r"
cask "rectangle"
cask "slack"
cask "stats"
cask "sublime-text"
cask "tencent-meeting"
cask "tor-browser"
cask "trex"
cask "typora"
cask "visual-studio-code"
cask "vlc"
cask "webex-meetings"
cask "wechat"
cask "wpsoffice"
cask "zettlr"
cask "zoom"
cask "zotero"
mas "AdBlock", id: 1402042596
mas "GoodNotes", id: 1444383602
mas "Keynote 讲演", id: 409183694
mas "LiquidText", id: 922765270
mas "MarginNote 3", id: 1423522373
mas "Notability", id: 736189492
mas "Numbers 表格", id: 409203825
mas "Pages 文稿", id: 409201541
mas "Purple Notebook", id: 1535269503
mas "Shapr3D", id: 1091675654
mas "Speedtest", id: 1153157709
mas "Twitter", id: 1482454543
mas "Xnip", id: 1221250572
mas "zClock Lite", id: 1489475245
mas "专注清单", id: 1258530160
mas "印象笔记", id: 1356055347
mas "欧路词典", id: 434350458
mas "闪电视频转换器", id: 1208467587
